### ISSUE TITLE
[AVM Module Issue]: Problem assigning custom roles

### ISSUE THREAD

**Issue by fmmcsilva** [Azure/terraform-azurerm-avm-res-authorization-roleassignment#58]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Issue Type?

Bug

### (Optional) Module Version

0.0.1

### Description

When using the module to assign a custom role to a resource, the module data source request for the custom role definition returns an error stating that it was unable to find the custom role name.

```
resource "azurerm_role_definition" "scaledown_aks" {
  name              = "sptto rd scaledown aks"
  scope             = "/subscriptions/${var.subscription_id}"
  description       = "This is a custom role created via Terraform to enable aks scaledown"
  assignable_scopes = ["/subscriptions/${var.subscription_id}", azurerm_kubernetes_cluster.this.id]

  permissions {
    actions = ["Microsoft.ContainerService/managedClusters/stop/action"]
  }
}



module "role_assignments" {
  source  = "Azure/avm-res-authorization-roleassignment/azurerm"
  version = "~> 0.0.1"



  user_assigned_managed_identities_by_principal_id = {
    github = module.github_managed_identity.principal_id
  }


  role_definitions = {
    scaledown_aks                     = azurerm_role_definition.scaledown_aks.name
  }

  role_assignments_for_resources = {
    "aks-github-downscale" = {
      resource_group_name = azurerm_resource_group.this.name
      resource_name       = azurerm_kubernetes_cluster.this.name
      role_assignments = {
        "scaledown_aks" = {
          role_definition                  = "scaledown_aks"
          user_assigned_managed_identities = ["github"]
        }
      }
    }
  }
}
```
Error:
```
│ Error: loading Role Definition List: could not find role 'sptto rd scaledown aks'
│ 
│   with module.role_assignments.data.azurerm_role_definition.role_definitions_by_name["scaledown_aks"],
│   on .terraform/modules/role_assignments/locals.role.definitions.tf line 15, in data "azurerm_role_definition" "role_definitions_by_name":
│   15: data "azurerm_role_definition" "role_definitions_by_name" {
│ 
│ loading Role Definition List: could not find role 'sptto rd scaledown aks'
```

The error points to the `locals.role.definitions.tf`
```
data "azurerm_role_definition" "role_definitions_by_name" {
  for_each = var.role_definitions

  name = each.value
}
```

According to the [AzureRM provider documentation](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/data-sources/role_definition#scope), with custom roles, the `scope` parameter must also be specified when using the `name` parameter.

**Comment by matt-FFFFFF** [comment]
@jaredfholgate seems like we need an optional attribute for the scope?

**Comment by jaredfholgate** [comment]
> @jaredfholgate seems like we need an optional attribute for the scope?

Thanks, will take a look. I have some improvement work to do on this module.

**Comment by ZdenekPesek** [comment]
Hi @jaredfholgate,
seems this behavior is not just for a custom roles as mentioned in https://github.com/hashicorp/terraform-provider-azurerm/issues/19847 as there is an usage of `Storage File Data SMB Share Contributor` within a data resource.
I am having the same issue with built-in roles described in https://github.com/Azure/terraform-azurerm-avm-res-authorization-roleassignment/issues/57. And hopefully adding of the scope attribute proposed by @matt-FFFFFF  could solve it for me.

Would not make sense to add also
```
data "azurerm_subscription" "primary" {}
```
as a default scope in https://github.com/Azure/terraform-azurerm-avm-res-authorization-roleassignment/blob/main/locals.role.definitions.tf#L15-L19  if not provided?

**Comment by jaredfholgate** [comment]
Added scope option in v0.1.0
