### ISSUE TITLE
[AVM Module Issue]: Add Principal Type to Role assignment

### ISSUE THREAD

**Issue by mennaammar** [Azure/terraform-azurerm-avm-res-authorization-roleassignment#61]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Issue Type?

Feature Request

### (Optional) Module Version

v0.0.1

### Description

We have a policy in Azure that only groups and service principals can be used in role assignment. When we used this module, we got error 403 error as the principal type is not supplied as part of the terraform code. 

Appreciate adding principal_type to 

resource "azurerm_role_assignment" "this" {
  for_each = local.role_assignments

  principal_id       = each.value.principal_id
  scope              = each.value.scope
  principal_type = each.value.type ----> needs to be added
  role_definition_id = each.value.role_definition_id
}

**Comment by jaredfholgate** [comment]
Released in v0.1.0
